// app.ts — Express app factory (no listen call — importable by Vercel)
// This file is auto-generated by Vercel migration.
// The original index.ts logic should be moved here.
// 
// If this file already exists, skip this step.
// Otherwise copy the contents of your index.ts here,
// remove the app.listen() call, and add: export default app
